### PR TITLE
Support Query Parameters for getAllGroups

### PR DESCRIPTION
**Pull request by AzmathIOU**
Support for Query Parameters for getAllGroups()

### CODE REVIEW

**Comment by AzmathIOU** [comment]
Thank you @andrea-patricelli for reviewing and providing feedback. The issue that i faced with Parameters passed as filters is, If you have Query Parameters, the URI ends up with  https://..../Groups?**filter=attributes%3Dmembers**. but actually it should end up as https://..../Groups?**attributes%3Dmembers** (without filter). If there are any filters then those will come as part of filter. like https://..../Groups?**filter= displayName+eq+SampleGroup**&attributes=members. 
Also i made the changes to get invoked from the SCIMv2Client as i referred the TestSuite(SCIMV2ConnectTests) which the project has and where i see the getAllGroups() calls invoked directly from Client without Connector. Appreciate if you could review and let me know your comments.

**Comment by AzmathIOU** [comment]
@andrea-patricelli .
 I have implemented the changes from SCIM Connector as well. 
 Note: I did not change the interface SearchOp by adding the new overloaded method as i felt that the interface may be implemented by many other connectors which might break. I added the method directly only for SCIM Connector. Please let me know if that is right inference. Thank you.

**Comment by ilgrosso** [comment]
@AzmathIOU I think you are completely missing the point here.

This project is part of a set of connectors based on the [ConnId](https://connid.tirasa.net) umbrella, whose purpose is to provide an extensible interface between a Provisioning Engine (as [Apache Syncope](https://syncope.apache.org)) and the target resources: a SCIM server, in this case, but also [several others](https://github.com/Tirasa/ConnId/blob/master/README.md#available-connectors).

Hence, whichever method you might add to {{AbstractSCIMConnector}}, being not part of the ConnId interface, no one will be invoking it anyway.

Again, this project is not about building a generic Java-based SCIM client.

**Comment by AzmathIOU** [comment]
Hi Francesco, 

Not sure how to reach out to you on email or JIRA(as the ticket got closed), so mentioning here. 

I understand your point for not fixing it as it's not invoked from the generic ConnId interface.But based on my research for a good available SCIM client, The ConnId SCIM bundle fits perfectly.
 The ConnId SCIM connector project has good design principles adopted. Implementing a Token fetch from the token Endpoint to the recent change of retry mechanism in case of token expiry added by andrea-patricelli. I really appreciate the thorough thoughtfulness that went into the design.The way the project handles the custom Schema and data model is something I have not seen in other projects. And last but not the least the issues being addressed promptly.

Appreciate if you could re-consider the use cases I am mentioning. I am ready to make changes myself and commit the code for the use cases I am raising. 
1) Support for query Parameters
2) Support /Me (if the resource is **User**)
3) Support for group membership PATCH without a complete REPLACE of the members.

Appreciate to hear back your thoughts/Comments/Suggestions. 

Thank you,
Azmath

**Comment by ilgrosso** [comment]
Hi @AzmathIOU ,
please do not duplicate the same message over multiple channels, as you did with the text above and the latest comment on [SCIM-22](https://connid.atlassian.net/browse/SCIM-22?focusedCommentId=15793).

I think we have already explained that the appropriate place for such discussion is the connid-dev@ forum, which you have already been able to send messages to.

As already explained above, this project is not meant for building a generic-purpose SCIM client: if you like the code, you are free to fork it and adjust it the way you like the most, that's the good of Open Source licenses as the [ALv2 license](https://github.com/Tirasa/ConnIdSCIMBundle/blob/master/LICENSE) under which this project is released.

About the three items above, these are the JIRA references in case anyone wants to read more:

1. [SCIM-22](https://connid.atlassian.net/browse/SCIM-22)
1. [SCIM-21](https://connid.atlassian.net/browse/SCIM-21)
1. [SCIM-23](https://connid.atlassian.net/browse/SCIM-23)

Please do not add further comments to this PR.

**Pull request closed without merging**
